"""initial tables

Revision ID: c9822c42ee8f
Revises: 
Create Date: 2026-05-12 15:32:54.875406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9822c42ee8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the new enum type first
    orgrole = sa.Enum('owner', 'admin', 'member', 'viewer', name='orgrole')
    orgrole.create(op.get_bind())

    # Alter the column to use the new enum (with explicit USING cast)
    op.execute("""
        ALTER TABLE org_memberships 
        ALTER COLUMN role TYPE orgrole 
        USING role::text::orgrole
    """)

    # Drop the old enum type
    op.execute("DROP TYPE IF EXISTS org_role")

    # Fix indexes on calls table
    op.drop_constraint('calls_provider_call_id_key', 'calls', type_='unique')
    op.drop_index('idx_calls_agent_id', table_name='calls')
    op.drop_index('idx_calls_created_at', table_name='calls')
    op.drop_index('idx_calls_org_id', table_name='calls')
    op.drop_index('idx_calls_outcome', table_name='calls')
    op.drop_index('idx_calls_provider_call_id', table_name='calls')
    op.drop_index('idx_calls_provider_type', table_name='calls')
    op.drop_index('idx_calls_status', table_name='calls')

    op.create_index(op.f('ix_calls_agent_id'), 'calls', ['agent_id'], unique=False)
    op.create_index(op.f('ix_calls_org_id'), 'calls', ['org_id'], unique=False)
    op.create_index(op.f('ix_calls_outcome'), 'calls', ['outcome'], unique=False)
    op.create_index(op.f('ix_calls_provider_call_id'), 'calls', ['provider_call_id'], unique=True)
    op.create_index(op.f('ix_calls_provider_type'), 'calls', ['provider_type'], unique=False)
    op.create_index(op.f('ix_calls_status'), 'calls', ['status'], unique=False)

    # Fix org_memberships indexes
    op.drop_index('idx_memberships_org_id', table_name='org_memberships')
    op.drop_index('idx_memberships_user_id', table_name='org_memberships')
    op.drop_constraint('uq_user_org', 'org_memberships', type_='unique')
    op.drop_column('org_memberships', 'updated_at')
    op.drop_column('org_memberships', 'created_at')

    # Fix organizations indexes
    op.drop_index('idx_organizations_slug', table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)

    # Fix refresh_tokens indexes
    op.drop_index('idx_refresh_tokens_jti', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_user_id', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)

    # Fix users indexes
    op.drop_index('idx_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)


def downgrade() -> None:
    # Reverse indexes
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_calls_status'), table_name='calls')
    op.drop_index(op.f('ix_calls_provider_type'), table_name='calls')
    op.drop_index(op.f('ix_calls_provider_call_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_outcome'), table_name='calls')
    op.drop_index(op.f('ix_calls_org_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_agent_id'), table_name='calls')

    # Reverse enum rename
    op.execute("""
        ALTER TABLE org_memberships
        ALTER COLUMN role TYPE org_role
        USING role::text::org_role
    """)
    op.execute("DROP TYPE IF EXISTS orgrole")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_organizations_slug'), 'organizations', ['slug'], unique=False)
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('org_memberships', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('org_memberships', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_user_org'), 'org_memberships', ['user_id', 'org_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_memberships_user_id'), 'org_memberships', ['user_id'], unique=False)
    op.create_index(op.f('idx_memberships_org_id'), 'org_memberships', ['org_id'], unique=False)
    op.alter_column('org_memberships', 'role',
               existing_type=sa.Enum('owner', 'admin', 'member', 'viewer', name='orgrole'),
               type_=postgresql.ENUM('owner', 'admin', 'member', 'viewer', name='org_role'),
               existing_nullable=False,
               existing_server_default=sa.text("'member'::org_role"))
    op.drop_index(op.f('ix_calls_status'), table_name='calls')
    op.drop_index(op.f('ix_calls_provider_type'), table_name='calls')
    op.drop_index(op.f('ix_calls_provider_call_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_outcome'), table_name='calls')
    op.drop_index(op.f('ix_calls_org_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_agent_id'), table_name='calls')
    op.create_index(op.f('idx_calls_status'), 'calls', ['status'], unique=False)
    op.create_index(op.f('idx_calls_provider_type'), 'calls', ['provider_type'], unique=False)
    op.create_index(op.f('idx_calls_provider_call_id'), 'calls', ['provider_call_id'], unique=False)
    op.create_index(op.f('idx_calls_outcome'), 'calls', ['outcome'], unique=False)
    op.create_index(op.f('idx_calls_org_id'), 'calls', ['org_id'], unique=False)
    op.create_index(op.f('idx_calls_created_at'), 'calls', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_calls_agent_id'), 'calls', ['agent_id'], unique=False)
    op.create_unique_constraint(op.f('calls_provider_call_id_key'), 'calls', ['provider_call_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
